# Generated by Django 3.0.14 on 2022-07-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20220713_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='last_time_logout',
        ),
        migrations.AddField(
            model_name='project',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
